version: "3.3"

services:
  fastapi:
    build: .
    command: "python3 ./src/main.py"
    ports:
      - "${FAST_API_EXTERNAL_PORT}:${FAST_API_INTERNAL_PORT}"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: "redis:latest"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "${ES_EXTERNAL_PORT}:${ES_INTERNAL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:{$ES_INTERNAL_PORT}/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3