version: "3.9"

services:
  redis:
    image: "redis:latest"
    networks:
      - elk_default

  fastapi:
    build: .
    command: "gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:${FAST_API_INTERNAL_PORT}"
    expose:
      - "${FAST_API_INTERNAL_PORT}"
    restart: on-failure
    volumes:
      - ./.env:/app/src/.env
      - ./logs/nginx/json-logs.json:/app/src/logs/auth_service.json
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - elk_default

  nginx:
    image: "nginx:1.25.3"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data/html:/data/html:ro
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - fastapi
    ports:
      - "80:80"
    networks:
      - elk_default

  tracer:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - METRICS_BACKEND=prometheus
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - elk_default

  filebeat:
    image: elastic/filebeat:8.10.2
    command: filebeat -e -strict.perms=false
    volumes:
      - ./logs/nginx:/var/log/nginx:ro
      - ./deploy/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk_default

networks:
  elk_default:
    name: elk_name